name: Meterian Scan

on:
  pull_request: { }
  push:
    branches: [ "main" ]

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Meterian Scanner
        uses: MeterianHQ/meterian-github-action@v1.0.17
        env:
          METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
        with:
          cli_args: --flags:gradle.root.only=false